### ISSUE TITLE
node-red reports timeout error while re-deploying

### ISSUE THREAD

**Issue by tinoue** [tinoue/node-red-contrib-linking-device#11]
再デプロイ時にflowをとめるのに15秒以上かかり、node-redでタイムアウトが発生している。
linking-deviceに問題がある可能性大。

```
18-08-18 13:39:04 [debug]  saved flow revision: 5a4e82b1e9faf60c95f71c44bb1267a7
18-08-18 13:39:04 [info]  Stopping flows
18-08-18 13:39:04 [debug]  red/nodes/flows.stop : stopping flow : global
18-08-18 13:39:04 [debug]  red/nodes/flows.stop : stopping flow : 2b09d8bf.0e4648
18-08-18 13:39:04 [info]  linking-scanner closing.
18-08-18 13:39:04 [info]  linking-scanner closed.
18-08-18 13:39:04 [debug]  linking-led Closing.
18-08-18 13:39:04 [debug]  linking-led Closed.
18-08-18 13:39:04 [info]  linking-sensor closing.
18-08-18 13:39:04 [info]  linking-sensor closed.
18-08-18 13:39:04 [info]  linking-sensor closing.
18-08-18 13:39:04 [info]  linking-sensor closed.
18-08-18 13:39:19 [error]  Error stopping node: TimeoutError: timed out after 15000ms
18-08-18 13:39:19 [debug]  TimeoutError: timed out after 15000ms
    at onTimeout (/home/pi/git/node-red-template-embedded/node_modules/when/lib/decorators/timed.js:69:7)
    at Timeout._onTimeout (/home/pi/git/node-red-template-embedded/node_modules/when/lib/decorators/timed.js:13:4)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
18-08-18 13:39:19 [info]  Stopped flows
```

**Comment by tinoue** [comment]
mqtt outノードが原因であることが判明。mqtt outノードへの配線を削除すると、問題なくデプロイが出来ることで確認。
