### ISSUE TITLE
noble: RangeError on Hci.processLeAdvertisingReport

### ISSUE THREAD

**Issue by tinoue** [tinoue/node-red-contrib-linking-device#14]
```
18-08-18 14:30:48 [info]  started sensor: humidity
18-08-18 14:30:48 [debug]  humidity notification started.
buffer.js:977
    throw new RangeError('Index out of range');
    ^

RangeError: Index out of range
    at checkOffset (buffer.js:977:11)
    at Buffer.readInt8 (buffer.js:1103:5)
    at Hci.processLeAdvertisingReport (/home/pi/git/node-red-contrib-linking-device/node_modules/noble/lib/hci-socket/hci.js:804:25)
    at Hci.processLeMetaEvent (/home/pi/git/node-red-contrib-linking-device/node_modules/noble/lib/hci-socket/hci.js:767:12)
    at Hci.onSocketData (/home/pi/git/node-red-contrib-linking-device/node_modules/noble/lib/hci-socket/hci.js:583:14)
    at emitOne (events.js:116:13)
    at BluetoothHciSocket.emit (events.js:211:7)
```

**Comment by tinoue** [comment]
repro +1
